export const DEFAULT_CATEGORIES = [
  'COMMON USED SUPPLIES',
  'PLANT, PROPERTY & EQUIPMENTS',
  'FUELS',
  'LUBRICANTS',
  'PLUMBING',
  'ELECTRICAL',
  'MEDICINE',
  'FOODSTUFF',
  'AGRICULTURAL SUPPLY',
  'SPAREPARTS',
  'COMPUTER & LAPTOP',
  'JANITORIAL SERVICES',
  'MEDICAL SUPPLY',
  'PERSONAL HYGIENE',
  'E-LOAD'
];